name: Deploy to Server

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Adjust this to your desired version

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

  build:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build the project
        run: npm run build

      - name: Verify build output
        run: ls -la dist

      - name: Save build output
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Retrieve build output
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist  # Ensure it's correctly extracted

      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: yavka
          port: 22
          key: ${{ secrets.DEPLOY_KEY }}
          source: "dist/*"
          target: "~/Archipelago-WEB/"

      - name: Var dir unpack
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: yavka
          port: 22
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            sudo rm -rf /var/www/html/*
            sudo cp -r ~/Archipelago-WEB/dist/* /var/www/html/