name: Deploy to Server

on:
  push:
    branches: [ main ]  # Adjust if you're using a different branch for deployment
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Adjust to the version you're using

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.6  # Or latest version
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: yavka
          port: 22
          key: ${{ secrets.DEPLOY_KEY }}
          source: "dist/*"
          target: "~/Archipelago-WEB/dist"
